// Copyright 2018 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file was generated by running:
//     ../../chrome/test/chromedriver/embed_js_in_cpp.py --directory gen/chrome/test/chromedriver/chrome ../../chrome/test/chromedriver/js/call_function.js ../../chrome/test/chromedriver/js/dispatch_touch_event.js ../../chrome/test/chromedriver/js/execute_async_script.js ../../chrome/test/chromedriver/js/execute_script.js ../../chrome/test/chromedriver/js/focus.js ../../chrome/test/chromedriver/js/get_element_location.js ../../chrome/test/chromedriver/js/get_element_region.js ../../chrome/test/chromedriver/js/is_option_element_toggleable.js

#ifndef CHROME_TEST_CHROMEDRIVER_CHROME_JS_H_
#define CHROME_TEST_CHROMEDRIVER_CHROME_JS_H_

namespace webdriver {
extern const char kCallFunctionScript[];
extern const char kDispatchTouchEventScript[];
extern const char kExecuteAsyncScriptScript[];
extern const char kExecuteScriptScript[];
extern const char kFocusScript[];
extern const char kGetElementLocationScript[];
extern const char kGetElementRegionScript[];
extern const char kIsOptionElementToggleableScript[];
}

#endif  // CHROME_TEST_CHROMEDRIVER_CHROME_JS_H_
